// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace veripark.ViewMode.Entities;

 
public   class BorrowerEntity
{
     
    public int Id { get; set; }

    
    public string Name { get; set; }

     
    public string Contact { get; set; }

    
    public string EmailId { get; set; }

    public bool IsActive { get; set; }

  
    public DateTime? OnDate { get; set; }
}