// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;


namespace veripark.ViewMode.Entities;

 
public   class CustomerEntity
{
    
    public int Id { get; set; }

    public int UserId { get; set; }

    public int NationalId { get; set; }
 
    public string FirstName { get; set; }

    
    public string LastName { get; set; }

    
    public string Gender { get; set; }

    public int? Age { get; set; }

    
    public string Address { get; set; }

    
    public string Contact { get; set; }

   
    public DateTime? OnDate { get; set; }
}