// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;


namespace veripark.ViewMode.Entities;

 
public   class HolidayMasterEntity
{
  
    public int Id { get; set; }

    
    public string HolidayTitle { get; set; }

   
    public DateTime? HolidayFromDate { get; set; }

    
    public DateTime? HolidayToDate { get; set; }

   
    public string Description { get; set; }

    public bool? IsActive { get; set; }

 
    public DateTime? OnDate { get; set; }
}