// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace veripark.ViewMode.Entities;

 
public   class RoleEntity
{
     
    public int Id { get; set; }

   
    public string Name { get; set; }

    public bool? IsActive { get; set; }
}