// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;


namespace veripark.ViewMode.Entities;

 
public class RoleInUserEntity
{
   
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? RoleId { get; set; }
}